### ISSUE TITLE
I think you are quite nice even without me :)

### ISSUE THREAD

**Issue by verbose9** [Jg-07/DropBox_Clone#1]

**Comment by verbose9** [comment]
I'm also leaving the web-development land because its too much here I'm now programming in C#, C++ and maybe later I _may_ start game development may be till that time you might be best at React or Svelte :)

And last thing is [this](http://threejs.org)

**Comment by Jg-07** [comment]
Sure but thanks for your support buddy
I learnt a lot of concepts from you dude
And even I have some plans regarding Three.js really good one to explore 
even I guess even most of the websites are going to be on 3D rather than 2d
